import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traduzioni
const translations = {
  it: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.deadlines': 'Scadenze',
    'nav.properties': 'Proprietà',
    'nav.vehicles': 'Veicoli',
    'nav.expenses': 'Spese',
    'nav.bookings': 'Prenotazioni B&B',
    'nav.workouts': 'Allenamenti',
    'nav.events': 'Eventi',
    'nav.documents': 'Documenti',
    'nav.contacts': 'Contatti',
    'nav.profile': 'Profilo',
    'nav.settings': 'Impostazioni',

    // Dashboard
    'dashboard.welcome': 'Benvenuto in VitaApp',
    'dashboard.subtitle': 'La tua soluzione completa per gestire proprietà, veicoli, spese e molto altro. Semplifica la tua vita con una dashboard intuitiva e potente.',
    'dashboard.getStarted': 'Inizia Ora',
    'dashboard.learnMore': 'Scopri di Più',
    'dashboard.pendingDeadlines': 'Scadenze Pendenti',
    'dashboard.totalExpenses': 'Spese Totali (Ultimi 30g)',
    'dashboard.activeProperties': 'Proprietà Attive',
    'dashboard.upcomingEvents': 'Prossimi Eventi',
    'dashboard.upcomingDeadlinesList': 'Prossime Scadenze',
    'dashboard.recentExpenses': 'Spese Recenti',
    'dashboard.viewAll': 'Vedi Tutto',
    'dashboard.completed': 'completate',
    'dashboard.total': 'Totale',
    'dashboard.fromRecentTransactions': 'Dalle transazioni recenti',
    'dashboard.rented': 'Affittate',
    'dashboard.vacant': 'Libere',
    'dashboard.next': 'Prossimo',
    'dashboard.noDeadlines': 'Nessuna scadenza pendente. Ben fatto!',
    'dashboard.noExpenses': 'Nessuna spesa registrata di recente.',
    'dashboard.activityOverview': 'Panoramica Attività',
    'dashboard.daysAgo': 'giorni fa',
    'dashboard.days': 'giorni',

    // Properties
    'properties.title': 'Gestione Proprietà',
    'properties.addNew': 'Aggiungi Nuova Proprietà',
    'properties.myProperties': 'Le Mie Proprietà',
    'properties.selectPrompt': 'Seleziona una proprietà per visualizzare i dettagli',
    'properties.table.property': 'Proprietà',
    'properties.table.type': 'Tipo',
    'properties.table.size': 'Dimensione',
    'properties.table.currentValue': 'Valore Corrente',
    'properties.table.actions': 'Azioni',
    'properties.details.title': 'Dettagli Proprietà',
    'properties.details.type': 'Tipo',
    'properties.details.size': 'Dimensione',
    'properties.details.purchaseDate': 'Data Acquisto',
    'properties.details.purchasePrice': 'Prezzo Acquisto',
    'properties.details.currentValue': 'Valore Corrente',
    'properties.details.valueChange': 'Variazione Valore',
    'properties.details.notes': 'Note',
    'properties.details.edit': 'Modifica Proprietà',
    'properties.details.viewDocuments': 'Vedi Documenti',
    'properties.mock.mainApartment.name': 'Appartamento Principale',
    'properties.mock.mainApartment.type': 'Appartamento',
    'properties.mock.mainApartment.notes': 'Residenza principale',
    'properties.mock.beachHouse.name': 'Casa al Mare',
    'properties.mock.beachHouse.type': 'Casa',
    'properties.mock.beachHouse.notes': 'Proprietà per vacanze e affitto B&B',
    'properties.mock.mountainCabin.name': 'Baita in Montagna',
    'properties.mock.mountainCabin.type': 'Baita',
    'properties.mock.mountainCabin.notes': 'Proprietà per vacanze invernali',

    // Deadlines
    'deadlines.title': 'Gestione Scadenze',
    'deadlines.addNew': 'Aggiungi Nuova Scadenza',
    'deadlines.filter.all': 'Tutte',
    'deadlines.filter.upcoming': 'Prossime',
    'deadlines.filter.completed': 'Completate',
    'deadlines.sortBy': 'Ordina per',
    'deadlines.sort.dueDate': 'Data Scadenza',
    'deadlines.sort.title': 'Titolo',
    'deadlines.sort.category': 'Categoria',
    'deadlines.table.status': 'Stato',
    'deadlines.table.title': 'Titolo',
    'deadlines.table.dueDate': 'Data Scadenza',
    'deadlines.table.category': 'Categoria',
    'deadlines.table.remainingTime': 'Tempo Rimanente',
    'deadlines.table.actions': 'Azioni',
    'deadlines.status.completed': 'Completata',
    'deadlines.days': 'giorni',
    'deadlines.category.taxes': 'Tasse',
    'deadlines.category.vehicle': 'Veicolo',
    'deadlines.mock.imuFirst': 'Primo Acconto IMU',
    'deadlines.mock.imuFirstDesc': 'Prima rata dell\'imposta municipale unica',
    'deadlines.mock.carInsurance': 'Rinnovo Assicurazione Auto',
    'deadlines.mock.carInsuranceDesc': 'Rinnovo annuale assicurazione auto',
    'deadlines.mock.tari': 'Pagamento TARI',
    'deadlines.mock.tariDesc': 'Pagamento annuale tassa sui rifiuti',
    'deadlines.mock.imuSecond': 'Secondo Acconto IMU',
    'deadlines.mock.imuSecondDesc': 'Seconda rata dell\'imposta municipale unica',
    'deadlines.mock.carTax': 'Rinnovo Bollo Auto',
    'deadlines.mock.carTaxDesc': 'Rinnovo bollo auto annuale',
    'deadlines.mock.vehicleInspection': 'Revisione Veicolo',
    'deadlines.mock.vehicleInspectionDesc': 'Controllo tecnico periodico del veicolo',

    // Vehicles
    'vehicles.title': 'Gestione Veicoli',
    'vehicles.addNew': 'Aggiungi Nuovo Veicolo',
    'vehicles.myVehicles': 'I Miei Veicoli',
    'vehicles.selectPrompt': 'Seleziona un veicolo per visualizzare i dettagli',
    'vehicles.type.car': 'Auto',
    'vehicles.type.motorcycle': 'Moto',
    'vehicles.table.vehicle': 'Veicolo',
    'vehicles.table.type': 'Tipo',
    'vehicles.table.licensePlate': 'Targa',
    'vehicles.table.insuranceExpiry': 'Scadenza Assicurazione',
    'vehicles.table.actions': 'Azioni',
    'vehicles.details.title': 'Dettagli Veicolo',
    'vehicles.details.type': 'Tipo',
    'vehicles.details.licensePlate': 'Targa',
    'vehicles.details.purchaseDate': 'Data Acquisto',
    'vehicles.details.purchasePrice': 'Prezzo Acquisto',
    'vehicles.details.currentValue': 'Valore Corrente',
    'vehicles.details.valueChange': 'Variazione Valore',
    'vehicles.details.importantDates': 'Date Importanti',
    'vehicles.details.insuranceRenewal': 'Rinnovo Assicurazione',
    'vehicles.details.registration': 'Bollo',
    'vehicles.details.annualCost': 'Costo Annuale',
    'vehicles.details.inspection': 'Revisione',
    'vehicles.details.lastInspection': 'Ultima Revisione',
    'vehicles.details.daysRemaining': 'giorni rimanenti',
    'vehicles.details.edit': 'Modifica Veicolo',
    'vehicles.details.viewDocuments': 'Vedi Documenti',
    'vehicles.mock.dailyDriver.name': 'Auto di tutti i giorni',
    'vehicles.mock.weekendRide.name': 'Moto del weekend',

    // Workouts
    'workouts.all': 'Tutti',
    'workouts.vsLastWeek': 'vs settimana scorsa',
    'workouts.type.strength': 'Forza',
    'workouts.type.cardio': 'Cardio',
    'workouts.type.flexibility': 'Flessibilità',
    'workouts.type.sports': 'Sport',
    'workouts.intensity.low': 'Bassa',
    'workouts.intensity.moderate': 'Moderata',
    'workouts.intensity.high': 'Alta',
    'workouts.intensity.extreme': 'Estrema',
    'workouts.mock.chestTriceps.name': 'Allenamento Petto e Tricipiti',
    'workouts.mock.chestTriceps.ex1': 'Panca piana',
    'workouts.mock.chestTriceps.ex2': 'Panca inclinata',
    'workouts.mock.chestTriceps.ex3': 'Parallele',
    'workouts.mock.chestTriceps.ex4': 'French press',
    'workouts.mock.chestTriceps.ex5': 'Push-up',
    'workouts.mock.chestTriceps.notes': 'Ottima sessione, aumentato il peso sulla panca',
    'workouts.mock.morningRun.name': 'Corsa Mattutina',
    'workouts.mock.morningRun.ex1': 'Corsa continua',
    'workouts.mock.morningRun.ex2': 'Sprint finali',
    'workouts.mock.morningRun.notes': 'Percorso parco cittadino, tempo migliorato',
    'workouts.mock.yoga.name': 'Yoga e Stretching',
    'workouts.mock.yoga.ex1': 'Saluto al sole',
    'workouts.mock.yoga.ex2': 'Warrior pose',
    'workouts.mock.yoga.ex3': 'Stretching catena posteriore',
    'workouts.mock.yoga.notes': 'Sessione rilassante, buona flessibilità',
    'workouts.mock.legDay.name': 'Allenamento Gambe',
    'workouts.mock.legDay.ex1': 'Squat',
    'workouts.mock.legDay.ex2': 'Leg press',
    'workouts.mock.legDay.ex3': 'Affondi',
    'workouts.mock.legDay.ex4': 'Stacchi rumeni',
    'workouts.mock.legDay.ex5': 'Polpacci',
    'workouts.mock.legDay.notes': 'Allenamento intenso, ottime sensazioni',
    'workouts.mock.tennis.name': 'Partita di Tennis',
    'workouts.mock.tennis.ex1': 'Servizio',
    'workouts.mock.tennis.ex2': 'Dritto',
    'workouts.mock.tennis.ex3': 'Rovescio',
    'workouts.mock.tennis.ex4': 'Volée',
    'workouts.mock.tennis.notes': 'Partita vinta 6-4, 6-3. Buon servizio oggi',
    'workouts.mock.hiit.name': 'HIIT Cardio',
    'workouts.mock.hiit.ex1': 'Burpees',
    'workouts.mock.hiit.ex2': 'Mountain climbers',
    'workouts.mock.hiit.ex3': 'Jump squats',
    'workouts.mock.hiit.ex4': 'High knees',
    'workouts.mock.hiit.notes': 'Intenso ma efficace, grande sudorazione',
    'workouts.mock.backBiceps.name': 'Allenamento Dorso e Bicipiti',
    'workouts.mock.backBiceps.ex1': 'Trazioni',
    'workouts.mock.backBiceps.ex2': 'Rematore',
    'workouts.mock.backBiceps.ex3': 'Lat machine',
    'workouts.mock.backBiceps.ex4': 'Curl bilanciere',
    'workouts.mock.backBiceps.ex5': 'Hammer curl',
    'workouts.mock.backBiceps.notes': 'Buona congestione, forma migliorata',

    // Events
    'events.all': 'Tutti',
    'events.list': 'Lista',
    'events.before': 'prima',
    'events.category.personal': 'Personale',
    'events.category.work': 'Lavoro',
    'events.category.health': 'Salute',
    'events.category.social': 'Sociale',
    'events.category.travel': 'Viaggio',
    'events.category.other': 'Altro',
    'events.mock.q2Review.title': 'Riunione di Lavoro - Q2 Review',
    'events.mock.q2Review.description': 'Revisione trimestrale dei risultati e pianificazione Q3',
    'events.mock.q2Review.location': 'Sala Conferenze A',
    'events.mock.medicalCheckup.title': 'Visita Medica - Controllo Generale',
    'events.mock.medicalCheckup.description': 'Check-up annuale dal medico di base',
    'events.mock.medicalCheckup.location': 'Studio Dr. Rossi, Via Roma 123',
    'events.mock.dinnerWithFriends.title': 'Cena con Amici',
    'events.mock.dinnerWithFriends.description': 'Cena di gruppo per festeggiare il compleanno di Marco',
    'events.mock.dinnerWithFriends.location': 'Ristorante Il Convivio',
    'events.mock.summerVacation.title': 'Partenza Vacanze Estive',
    'events.mock.summerVacation.description': 'Volo per Barcellona - Vacanza di una settimana',
    'events.mock.summerVacation.location': 'Aeroporto Malpensa - Terminal 1',
    'events.mock.photographyCourse.title': 'Corso di Fotografia',
    'events.mock.photographyCourse.description': 'Lezione 3: Tecniche di illuminazione naturale',
    'events.mock.photographyCourse.location': 'Centro Culturale, Aula 5',
    'events.mock.projectPresentation.title': 'Presentazione Progetto',
    'events.mock.projectPresentation.description': 'Presentazione finale del progetto VitaApp al cliente',
    'events.mock.projectPresentation.location': 'Ufficio Cliente, Milano Centro',
    'events.mock.giuliaWedding.title': 'Matrimonio di Giulia',
    'events.mock.giuliaWedding.description': 'Cerimonia e ricevimento',
    'events.mock.giuliaWedding.location': 'Villa San Martino, Lecco',
    'events.mock.personalTrainer.title': 'Allenamento Personal Trainer',
    'events.mock.personalTrainer.description': 'Sessione focalizzata su gambe e core',
    'events.mock.personalTrainer.location': 'Palestra FitZone',

    // Documents
    'documents.storageUsage': 'Utilizzo Spazio Archiviazione',
    'documents.usedPercentage': '{percentage}% utilizzato',
    'documents.allCategories': 'Tutte le Categorie',
    'documents.sortBy.date': 'Data Modifica',
    'documents.sortBy.name': 'Nome',
    'documents.sortBy.size': 'Dimensione',
    'documents.noDocumentsFound': 'Nessun documento trovato',
    'documents.tryDifferentFilters': 'Prova a modificare i filtri di ricerca',
    'documents.shared': 'Condiviso',
    'documents.category.personal': 'Personali',
    'documents.category.financial': 'Finanziari',
    'documents.category.legal': 'Legali',
    'documents.category.medical': 'Medici',
    'documents.category.contracts': 'Contratti',
    'documents.category.taxes': 'Tasse',
    'documents.category.insurance': 'Assicurazioni',
    'documents.category.other': 'Altri',
    'documents.mock.rentContract.name': 'Contratto Affitto Casa Milano.pdf',
    'documents.mock.taxReturn.name': 'Dichiarazione Redditi 2024.pdf',
    'documents.mock.familyBudget.name': 'Bilancio Familiare 2025.xlsx',
    'documents.mock.carInsurance.name': 'Assicurazione Auto Polizza.pdf',
    'documents.mock.bloodTests.name': 'Esami del Sangue Giugno.pdf',
    'documents.mock.idPhotos.name': 'Foto Documenti Identità',
    'documents.mock.workContract.name': 'Contratto Lavoro VitaApp.pdf',
    'documents.mock.utilityBills.name': 'Fatture Utenze Q1 2025.xlsx',
    'documents.mock.projectNotes.name': 'Note Progetto Casa.txt',
    'documents.mock.medicalReceipts.name': 'Ricevute Mediche 2025.pdf',

    // Settings
    'settings.subtitle': 'Personalizza la tua esperienza con VitaApp',
    'settings.notificationsDesc': 'Gestisci quando e come ricevere le notifiche',
    'settings.expenseNotifications': 'Notifiche Spese',
    'settings.bookingNotifications': 'Notifiche Prenotazioni',
    'settings.privacyDesc': 'Controlla la privacy dei tuoi dati',
    'settings.exportData.title': 'Esporta i miei dati',
    'settings.exportData.desc': 'Scarica una copia di tutti i tuoi dati',
    'settings.cookieManagement.title': 'Gestione Cookie',
    'settings.cookieManagement.desc': 'Personalizza le preferenze sui cookie',
    'settings.accountDesc': 'Gestisci il tuo account VitaApp',
    'settings.demoUser.name': 'Utente Demo',
    'settings.editProfile': 'Modifica Profilo',
    'settings.changePassword': 'Cambia Password',
    'settings.aboutDesc': 'Informazioni su VitaApp',
    'settings.lastUpdate': 'Ultimo Aggiornamento',
    'settings.releaseNotes': 'Note di Rilascio',
    'settings.support': 'Supporto',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.unsavedChanges.title': 'Modifiche non salvate',
    'settings.unsavedChanges.desc': 'Hai delle modifiche in sospeso. Salvale per applicarle.',

    // Expenses
    'expenses.fetchError': 'Errore nel caricamento delle spese',
    'expenses.deleteSuccess': 'Spesa eliminata con successo',
     'expenses.deleteError': 'Errore durante l\'eliminazione della spesa',
     'expenses.numberOfExpenses': 'Numero Spese',
     'expenses.noExpensesFound': 'Nessuna spesa trovata',
    'expenses.addFirstExpense': 'Inizia aggiungendo la tua prima spesa',
    'expenses.addFirstExpenseButton': 'Aggiungi Prima Spesa',
    'expenses.itemType': 'spesa',
    'expenses.category.food': 'Alimentari',
    'expenses.category.transport': 'Trasporti',
    'expenses.category.utilities': 'Utenze',
    'expenses.category.entertainment': 'Intrattenimento',
    'expenses.category.health': 'Salute',
    'expenses.category.shopping': 'Shopping',
    'expenses.category.education': 'Formazione',
    'expenses.category.other': 'Altro',
    'expenses.paymentMethod.card': 'Carta',
    'expenses.paymentMethod.cash': 'Contanti',
    'expenses.paymentMethod.transfer': 'Bonifico',
    'expenses.paymentMethod.check': 'Assegno',
    'expenses.mock.grocery.title': 'Spesa Alimentari',
    'expenses.mock.grocery.description': 'Spesa settimanale Esselunga',
    'expenses.mock.electricity.title': 'Bolletta Elettricità',
    'expenses.mock.electricity.description': 'Bolletta mensile elettricità',
    'expenses.mock.fuel.title': 'Carburante',
    'expenses.mock.fuel.description': 'Rifornimento Fiat 500',
    'expenses.mock.internet.title': 'Abbonamento Internet',
    'expenses.mock.internet.description': 'Canone mensile fibra',
    'expenses.mock.restaurant.title': 'Cena Ristorante',
    'expenses.mock.restaurant.description': 'Cena da Luigi',
    'expenses.mock.phone.title': 'Abbonamento Telefono',
    'expenses.mock.phone.description': 'Piano mobile mensile',

    // Bookings
    'bookings.all': 'Tutte',
    'bookings.status.confirmed': 'Confermata',
    'bookings.status.pending': 'In Attesa',
    'bookings.status.cancelled': 'Cancellata',
    'bookings.nights': 'notti',
    'bookings.note': 'Note',
    'bookings.mock.marcoRossi.guestName': 'Marco Rossi',
    'bookings.mock.marcoRossi.specialRequests': 'Check-in tardivo',
    'bookings.mock.annaWeber.guestName': 'Anna Weber',
    'bookings.mock.annaWeber.specialRequests': 'Culla per bambino',
    'bookings.mock.jeanDupont.guestName': 'Jean Dupont',
    'bookings.mock.jeanDupont.source': 'Diretto',
    'bookings.mock.sarahJohnson.guestName': 'Sarah Johnson',
    'bookings.mock.sarahJohnson.specialRequests': 'Posto auto',
    'bookings.mock.giuseppeBianchi.guestName': 'Giuseppe Bianchi',


    // Expenses
    'expenses.title': 'Gestione Spese',
    'expenses.addNew': 'Aggiungi Nuova Spesa',
    'expenses.allTime': 'Tutto il Tempo',
    'expenses.thisMonth': 'Questo Mese',
    'expenses.thisYear': 'Quest\'Anno',
    'expenses.sortBy': 'Ordina per:',
    'expenses.date': 'Data',
    'expenses.amount': 'Importo',
    'expenses.category': 'Categoria',
    'expenses.myExpenses': 'Le Mie Spese',
    'expenses.total': 'Totale',
    'expenses.expense': 'Spesa',
    'expenses.actions': 'Azioni',
    'expenses.edit': 'Modifica',
    'expenses.delete': 'Elimina',
    'expenses.details': 'Dettagli Spesa',
    'expenses.description': 'Descrizione',
    'expenses.paymentMethod': 'Metodo di Pagamento',
    'expenses.editExpense': 'Modifica Spesa',
    'expenses.viewReceipt': 'Visualizza Scontrino',
    'expenses.selectExpense': 'Seleziona una spesa per visualizzare i dettagli',
    'expenses.statistics': 'Statistiche Spese',
    'expenses.totalExpenses': 'Spese Totali',
    'expenses.averageExpense': 'Spesa Media',
    'expenses.byCategory': 'Spese per Categoria',
    'expenses.highestExpense': 'Spesa Più Alta',

    // B&B Bookings
    'bookings.title': 'Gestione Prenotazioni B&B',
    'bookings.addNew': 'Nuova Prenotazione',
    'bookings.calendar': 'Calendario',
    'bookings.upcoming': 'Prossime Prenotazioni',
    'bookings.checkin': 'Check-in',
    'bookings.checkout': 'Check-out',
    'bookings.guests': 'Ospiti',
    'bookings.revenue': 'Ricavo',
    'bookings.status': 'Stato',
    'bookings.confirmed': 'Confermata',
    'bookings.pending': 'In Attesa',
    'bookings.cancelled': 'Cancellata',
    'bookings.contact': 'Contatta',
    'bookings.viewDetails': 'Vedi Dettagli',
    'bookings.monthlyStats': 'Statistiche Mensili',
    'bookings.totalRevenue': 'Ricavo Totale',
    'bookings.occupancyRate': 'Tasso di Occupazione',
    'bookings.avgNightlyRate': 'Tariffa Media Notte',
    'bookings.totalBookings': 'Prenotazioni Totali',

    // Workouts
    'workouts.title': 'I Miei Allenamenti',
    'workouts.addNew': 'Nuovo Allenamento',
    'workouts.recent': 'Allenamenti Recenti',
    'workouts.duration': 'Durata',
    'workouts.exercises': 'Esercizi',
    'workouts.type': 'Tipo',
    'workouts.intensity': 'Intensità',
    'workouts.calories': 'Calorie',
    'workouts.notes': 'Note',
    'workouts.startWorkout': 'Inizia Allenamento',
    'workouts.viewDetails': 'Vedi Dettagli',
    'workouts.progress': 'Progressi',
    'workouts.thisWeek': 'Questa Settimana',
    'workouts.totalWorkouts': 'Allenamenti Totali',
    'workouts.totalTime': 'Tempo Totale',
    'workouts.avgDuration': 'Durata Media',
    'workouts.caloriesBurned': 'Calorie Bruciate',
    'workouts.strength': 'Forza',
    'workouts.cardio': 'Cardio',
    'workouts.flexibility': 'Flessibilità',
    'workouts.sports': 'Sport',
    'workouts.low': 'Bassa',
    'workouts.moderate': 'Moderata',
    'workouts.high': 'Alta',
    'workouts.extreme': 'Estrema',

    // Events
    'events.title': 'I Miei Eventi',
    'events.addNew': 'Nuovo Evento',
    'events.upcoming': 'Prossimi Eventi',
    'events.calendar': 'Calendario',
    'events.today': 'Oggi',
    'events.tomorrow': 'Domani',
    'events.thisWeek': 'Questa Settimana',
    'events.time': 'Orario',
    'events.location': 'Luogo',
    'events.attendees': 'Partecipanti',
    'events.reminder': 'Promemoria',
    'events.edit': 'Modifica',
    'events.delete': 'Elimina',
    'events.personal': 'Personale',
    'events.work': 'Lavoro',
    'events.health': 'Salute',
    'events.social': 'Sociale',
    'events.travel': 'Viaggio',
    'events.other': 'Altro',
    'events.noEvents': 'Nessun evento in programma',
    'events.createFirst': 'Crea il tuo primo evento!',

    // Documents
    'documents.title': 'I Miei Documenti',
    'documents.upload': 'Carica Documento',
    'documents.recent': 'Documenti Recenti',
    'documents.categories': 'Categorie',
    'documents.search': 'Cerca documenti...',
    'documents.name': 'Nome',
    'documents.size': 'Dimensione',
    'documents.modified': 'Modificato',
    'documents.type': 'Tipo',
    'documents.download': 'Scarica',
    'documents.share': 'Condividi',
    'documents.rename': 'Rinomina',
    'documents.move': 'Sposta',
    'documents.personal': 'Personali',
    'documents.financial': 'Finanziari',
    'documents.legal': 'Legali',
    'documents.medical': 'Medici',
    'documents.contracts': 'Contratti',
    'documents.taxes': 'Tasse',
    'documents.insurance': 'Assicurazioni',
    'documents.other': 'Altri',
    'documents.totalStorage': 'Spazio Totale',
    'documents.usedStorage': 'Spazio Utilizzato',
    'documents.freeStorage': 'Spazio Libero',

    // Settings
    'settings.title': 'Impostazioni',
    'settings.language': 'Lingua',
    'settings.theme': 'Tema',
    'settings.notifications': 'Notifiche',
    'settings.privacy': 'Privacy',
    'settings.account': 'Account',
    'settings.about': 'Informazioni',
    'settings.languageDesc': 'Seleziona la lingua dell\'interfaccia',
    'settings.themeDesc': 'Scegli tra tema chiaro o scuro',
    'settings.light': 'Chiaro',
    'settings.dark': 'Scuro',
    'settings.auto': 'Automatico',
    'settings.emailNotifications': 'Notifiche Email',
    'settings.pushNotifications': 'Notifiche Push',
    'settings.deadlineReminders': 'Promemoria Scadenze',
    'settings.save': 'Salva Modifiche',
    'settings.cancel': 'Annulla',
    'settings.version': 'Versione',
    'settings.developer': 'Sviluppatore',

    // Profile
    'profile.title': 'Il Mio Profilo',
    'profile.subtitle': 'Gestisci le tue informazioni personali',
    'profile.name': 'Nome',
    'profile.namePlaceholder': 'Inserisci il tuo nome',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'Inserisci la tua email',
    'profile.phone': 'Telefono',
    'profile.phonePlaceholder': 'Inserisci il tuo numero di telefono',
    'profile.address': 'Indirizzo',
    'profile.addressPlaceholder': 'Inserisci il tuo indirizzo',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Parlaci un po\' di te...',
    'profile.fetchError': 'Errore nel caricamento del profilo',
    'profile.saveSuccess': 'Profilo salvato con successo',
    'profile.saveError': 'Errore durante il salvataggio del profilo',
    'profile.namePlaceholder': 'Inserisci il tuo nome completo',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'Inserisci la tua email',
    'profile.phone': 'Telefono',
    'profile.phonePlaceholder': 'Inserisci il tuo numero di telefono',
    'profile.address': 'Indirizzo',
    'profile.addressPlaceholder': 'Inserisci il tuo indirizzo',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Parlaci un po\' di te...',
    'profile.fetchError': 'Errore nel caricamento del profilo',
    'profile.saveSuccess': 'Profilo salvato con successo',
    'profile.saveError': 'Errore durante il salvataggio del profilo',
    'common.loading': 'Caricamento...',
    'common.saving': 'Salvataggio...',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.add': 'Aggiungi',
    'common.search': 'Cerca...',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.view': 'Visualizza',
    'common.download': 'Scarica',
    'common.upload': 'Carica',
    'common.share': 'Condividi',
    'common.close': 'Chiudi',
    'common.confirm': 'Conferma',
    'common.warning': 'Attenzione',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.info': 'Informazione',
    'common.logout': 'Esci',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.deadlines': 'Deadlines',
    'nav.properties': 'Properties',
    'nav.vehicles': 'Vehicles',
    'nav.expenses': 'Expenses',
    'nav.bookings': 'B&B Bookings',
    'nav.workouts': 'Workouts',
    'nav.events': 'Events',
    'nav.documents': 'Documents',
    'nav.contacts': 'Contacts',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',

    // Dashboard
    'dashboard.welcome': 'Welcome to VitaApp',
    'dashboard.subtitle': 'Your all-in-one solution for managing properties, vehicles, expenses, and much more. Streamline your life with an intuitive and powerful dashboard.',
    'dashboard.getStarted': 'Get Started',
    'dashboard.learnMore': 'Learn More',
    'dashboard.pendingDeadlines': 'Pending Deadlines',
    'dashboard.totalExpenses': 'Total Expenses (Last 30d)',
    'dashboard.activeProperties': 'Active Properties',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.upcomingDeadlinesList': 'Upcoming Deadlines',
    'dashboard.recentExpenses': 'Recent Expenses',
    'dashboard.viewAll': 'View All',
    'dashboard.completed': 'completed',
    'dashboard.total': 'Total',
    'dashboard.fromRecentTransactions': 'From recent transactions',
    'dashboard.rented': 'Rented',
    'dashboard.vacant': 'Vacant',
    'dashboard.next': 'Next',
    'dashboard.noDeadlines': 'No pending deadlines. Well done!',
    'dashboard.noExpenses': 'No recent expenses logged.',
    'dashboard.activityOverview': 'Activity Overview',
    'dashboard.daysAgo': 'days ago',
    'dashboard.days': 'days',

    // Properties
    'properties.title': 'Property Management',
    'properties.addNew': 'Add New Property',
    'properties.myProperties': 'My Properties',
    'properties.selectPrompt': 'Select a property to view details',
    'properties.table.property': 'Property',
    'properties.table.type': 'Type',
    'properties.table.size': 'Size',
    'properties.table.currentValue': 'Current Value',
    'properties.table.actions': 'Actions',
    'properties.details.title': 'Property Details',
    'properties.details.type': 'Type',
    'properties.details.size': 'Size',
    'properties.details.purchaseDate': 'Purchase Date',
    'properties.details.purchasePrice': 'Purchase Price',
    'properties.details.currentValue': 'Current Value',
    'properties.details.valueChange': 'Value Change',
    'properties.details.notes': 'Notes',
    'properties.details.edit': 'Edit Property',
    'properties.details.viewDocuments': 'View Documents',
    'properties.mock.mainApartment.name': 'Main Apartment',
    'properties.mock.mainApartment.type': 'Apartment',
    'properties.mock.mainApartment.notes': 'Primary residence',
    'properties.mock.beachHouse.name': 'Beach House',
    'properties.mock.beachHouse.type': 'House',
    'properties.mock.beachHouse.notes': 'Vacation property and B&B rental',
    'properties.mock.mountainCabin.name': 'Mountain Cabin',
    'properties.mock.mountainCabin.type': 'Cabin',
    'properties.mock.mountainCabin.notes': 'Winter vacation property',

    // Deadlines
    'deadlines.title': 'Deadlines Management',
    'deadlines.addNew': 'Add New Deadline',
    'deadlines.filter.all': 'All',
    'deadlines.filter.upcoming': 'Upcoming',
    'deadlines.filter.completed': 'Completed',
    'deadlines.sortBy': 'Sort by',
    'deadlines.sort.dueDate': 'Due Date',
    'deadlines.sort.title': 'Title',
    'deadlines.sort.category': 'Category',
    'deadlines.table.status': 'Status',
    'deadlines.table.title': 'Title',
    'deadlines.table.dueDate': 'Due Date',
    'deadlines.table.category': 'Category',
    'deadlines.table.remainingTime': 'Remaining Time',
    'deadlines.table.actions': 'Actions',
    'deadlines.status.completed': 'Completed',
    'deadlines.days': 'days',
    'deadlines.category.taxes': 'Taxes',
    'deadlines.category.vehicle': 'Vehicle',
    'deadlines.mock.imuFirst': 'IMU First Payment',
    'deadlines.mock.imuFirstDesc': 'First installment of municipal property tax',
    'deadlines.mock.carInsurance': 'Car Insurance Renewal',
    'deadlines.mock.carInsuranceDesc': 'Annual car insurance renewal',
    'deadlines.mock.tari': 'TARI Payment',
    'deadlines.mock.tariDesc': 'Annual waste tax payment',
    'deadlines.mock.imuSecond': 'IMU Second Payment',
    'deadlines.mock.imuSecondDesc': 'Second installment of municipal property tax',
    'deadlines.mock.carTax': 'Car Tax Renewal',
    'deadlines.mock.carTaxDesc': 'Annual car tax renewal',
    'deadlines.mock.vehicleInspection': 'Vehicle Inspection',
    'deadlines.mock.vehicleInspectionDesc': 'Periodic technical inspection of the vehicle',
    'deadlines.fillAllFields': 'Please fill in all required fields.',
    'deadlines.errorAdding': 'Could not add deadline.',
    'deadlines.priority': 'Priority',
    'deadlines.priority.low': 'Low',
    'deadlines.priority.medium': 'Medium',
    'deadlines.priority.high': 'High',
    'deadlines.priority.urgent': 'Urgent',

    // Vehicles
    'vehicles.title': 'Vehicles Management',
    'vehicles.addNew': 'Add New Vehicle',
    'vehicles.myVehicles': 'My Vehicles',
    'vehicles.selectPrompt': 'Select a vehicle to view details',
    'vehicles.type.car': 'Car',
    'vehicles.type.motorcycle': 'Motorcycle',
    'vehicles.table.vehicle': 'Vehicle',
    'vehicles.table.type': 'Type',
    'vehicles.table.licensePlate': 'License Plate',
    'vehicles.table.insuranceExpiry': 'Insurance Expiry',
    'vehicles.table.actions': 'Actions',
    'vehicles.details.title': 'Vehicle Details',
    'vehicles.details.type': 'Type',
    'vehicles.details.licensePlate': 'License Plate',
    'vehicles.details.purchaseDate': 'Purchase Date',
    'vehicles.details.purchasePrice': 'Purchase Price',
    'vehicles.details.currentValue': 'Current Value',
    'vehicles.details.valueChange': 'Value Change',
    'vehicles.details.importantDates': 'Important Dates',
    'vehicles.details.insuranceRenewal': 'Insurance Renewal',
    'vehicles.details.registration': 'Registration',
    'vehicles.details.annualCost': 'Annual Cost',
    'vehicles.details.inspection': 'Inspection',
    'vehicles.details.lastInspection': 'Last Inspection',
    'vehicles.details.daysRemaining': 'days remaining',
    'vehicles.details.edit': 'Edit Vehicle',
    'vehicles.details.viewDocuments': 'View Documents',
    'vehicles.mock.dailyDriver.name': 'Daily Driver',
    'vehicles.mock.weekendRide.name': 'Weekend Ride',

    // Workouts
    'workouts.all': 'All',
    'workouts.vsLastWeek': 'vs last week',
    'workouts.type.strength': 'Strength',
    'workouts.type.cardio': 'Cardio',
    'workouts.type.flexibility': 'Flexibility',
    'workouts.type.sports': 'Sports',
    'workouts.intensity.low': 'Low',
    'workouts.intensity.moderate': 'Moderate',
    'workouts.intensity.high': 'High',
    'workouts.intensity.extreme': 'Extreme',
    'workouts.mock.chestTriceps.name': 'Chest & Triceps Workout',
    'workouts.mock.chestTriceps.ex1': 'Bench press',
    'workouts.mock.chestTriceps.ex2': 'Incline bench press',
    'workouts.mock.chestTriceps.ex3': 'Dips',
    'workouts.mock.chestTriceps.ex4': 'French press',
    'workouts.mock.chestTriceps.ex5': 'Push-up',
    'workouts.mock.chestTriceps.notes': 'Great session, increased weight on the bench press',
    'workouts.mock.morningRun.name': 'Morning Run',
    'workouts.mock.morningRun.ex1': 'Continuous run',
    'workouts.mock.morningRun.ex2': 'Final sprints',
    'workouts.mock.morningRun.notes': 'City park route, improved time',
    'workouts.mock.yoga.name': 'Yoga & Stretching',
    'workouts.mock.yoga.ex1': 'Sun salutation',
    'workouts.mock.yoga.ex2': 'Warrior pose',
    'workouts.mock.yoga.ex3': 'Posterior chain stretch',
    'workouts.mock.yoga.notes': 'Relaxing session, good flexibility',
    'workouts.mock.legDay.name': 'Leg Day',
    'workouts.mock.legDay.ex1': 'Squat',
    'workouts.mock.legDay.ex2': 'Leg press',
    'workouts.mock.legDay.ex3': 'Lunges',
    'workouts.mock.legDay.ex4': 'Romanian deadlifts',
    'workouts.mock.legDay.ex5': 'Calf raises',
    'workouts.mock.legDay.notes': 'Intense workout, great feeling',
    'workouts.mock.tennis.name': 'Tennis Match',
    'workouts.mock.tennis.ex1': 'Serve',
    'workouts.mock.tennis.ex2': 'Forehand',
    'workouts.mock.tennis.ex3': 'Backhand',
    'workouts.mock.tennis.ex4': 'Volley',
    'workouts.mock.tennis.notes': 'Match won 6-4, 6-3. Good serve today',
    'workouts.mock.hiit.name': 'HIIT Cardio',
    'workouts.mock.hiit.ex1': 'Burpees',
    'workouts.mock.hiit.ex2': 'Mountain climbers',
    'workouts.mock.hiit.ex3': 'Jump squats',
    'workouts.mock.hiit.ex4': 'High knees',
    'workouts.mock.hiit.notes': 'Intense but effective, great sweat',
    'workouts.mock.backBiceps.name': 'Back & Biceps Workout',
    'workouts.mock.backBiceps.ex1': 'Pull-ups',
    'workouts.mock.backBiceps.ex2': 'Row',
    'workouts.mock.backBiceps.ex3': 'Lat machine',
    'workouts.mock.backBiceps.ex4': 'Barbell curl',
    'workouts.mock.backBiceps.ex5': 'Hammer curl',
    'workouts.mock.backBiceps.notes': 'Good pump, improved form',

    // Events
    'events.all': 'All',
    'events.list': 'List',
    'events.before': 'before',
    'events.category.personal': 'Personal',
    'events.category.work': 'Work',
    'events.category.health': 'Health',
    'events.category.social': 'Social',
    'events.category.travel': 'Travel',
    'events.category.other': 'Other',
    'events.mock.q2Review.title': 'Work Meeting - Q2 Review',
    'events.mock.q2Review.description': 'Quarterly results review and Q3 planning',
    'events.mock.q2Review.location': 'Conference Room A',
    'events.mock.medicalCheckup.title': 'Medical Check-up - General Control',
    'events.mock.medicalCheckup.description': 'Annual check-up with the general practitioner',
    'events.mock.medicalCheckup.location': 'Dr. Rossi\'s Office, Via Roma 123',
    'events.mock.dinnerWithFriends.title': 'Dinner with Friends',
    'events.mock.dinnerWithFriends.description': 'Group dinner to celebrate Marco\'s birthday',
    'events.mock.dinnerWithFriends.location': 'Il Convivio Restaurant',
    'events.mock.summerVacation.title': 'Summer Vacation Departure',
    'events.mock.summerVacation.description': 'Flight to Barcelona - One week vacation',
    'events.mock.summerVacation.location': 'Malpensa Airport - Terminal 1',
    'events.mock.photographyCourse.title': 'Photography Course',
    'events.mock.photographyCourse.description': 'Lesson 3: Natural lighting techniques',
    'events.mock.photographyCourse.location': 'Cultural Center, Classroom 5',
    'events.mock.projectPresentation.title': 'Project Presentation',
    'events.mock.projectPresentation.description': 'Final presentation of the VitaApp project to the client',
    'events.mock.projectPresentation.location': 'Client\'s Office, Milan Center',
    'events.mock.giuliaWedding.title': 'Giulia\'s Wedding',
    'events.mock.giuliaWedding.description': 'Ceremony and reception',
    'events.mock.giuliaWedding.location': 'Villa San Martino, Lecco',
    'events.mock.personalTrainer.title': 'Personal Trainer Workout',
    'events.mock.personalTrainer.description': 'Session focused on legs and core',
    'events.mock.personalTrainer.location': 'FitZone Gym',

    // Documents
    'documents.storageUsage': 'Storage Usage',
    'documents.usedPercentage': '{percentage}% used',
    'documents.allCategories': 'All Categories',
    'documents.sortBy.date': 'Date Modified',
    'documents.sortBy.name': 'Name',
    'documents.sortBy.size': 'Size',
    'documents.noDocumentsFound': 'No documents found',
    'documents.tryDifferentFilters': 'Try changing the search filters',
    'documents.shared': 'Shared',
    'documents.category.personal': 'Personal',
    'documents.category.financial': 'Financial',
    'documents.category.legal': 'Legal',
    'documents.category.medical': 'Medical',
    'documents.category.contracts': 'Contracts',
    'documents.category.taxes': 'Taxes',
    'documents.category.insurance': 'Insurance',
    'documents.category.other': 'Other',
    'documents.mock.rentContract.name': 'Milan Home Rent Contract.pdf',
    'documents.mock.taxReturn.name': '2024 Tax Return.pdf',
    'documents.mock.familyBudget.name': '2025 Family Budget.xlsx',
    'documents.mock.carInsurance.name': 'Car Insurance Policy.pdf',
    'documents.mock.bloodTests.name': 'June Blood Tests.pdf',
    'documents.mock.idPhotos.name': 'ID Documents Photos',
    'documents.mock.workContract.name': 'VitaApp Work Contract.pdf',
    'documents.mock.utilityBills.name': 'Q1 2025 Utility Bills.xlsx',
    'documents.mock.projectNotes.name': 'House Project Notes.txt',
    'documents.mock.medicalReceipts.name': '2025 Medical Receipts.pdf',

    // Settings
    'settings.subtitle': 'Customize your VitaApp experience',
    'settings.notificationsDesc': 'Manage when and how you receive notifications',
    'settings.expenseNotifications': 'Expense Notifications',
    'settings.bookingNotifications': 'Booking Notifications',
    'settings.privacyDesc': 'Control your data privacy',
    'settings.exportData.title': 'Export my data',
    'settings.exportData.desc': 'Download a copy of all your data',
    'settings.cookieManagement.title': 'Cookie Management',
    'settings.cookieManagement.desc': 'Customize your cookie preferences',
    'settings.accountDesc': 'Manage your VitaApp account',
    'settings.demoUser.name': 'Demo User',
    'settings.editProfile': 'Edit Profile',
    'settings.changePassword': 'Change Password',
    'settings.aboutDesc': 'Information about VitaApp',
    'settings.lastUpdate': 'Last Update',
    'settings.releaseNotes': 'Release Notes',
    'settings.support': 'Support',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.unsavedChanges.title': 'Unsaved Changes',
    'settings.unsavedChanges.desc': 'You have pending changes. Save them to apply.',

    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information',
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Enter your full name',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'Enter your email address',
    'profile.phone': 'Phone',
    'profile.phonePlaceholder': 'Enter your phone number',
    'profile.address': 'Address',
    'profile.addressPlaceholder': 'Enter your address',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us a bit about yourself...',
    'profile.fetchError': 'Error loading profile',
    'profile.saveSuccess': 'Profile saved successfully',
    'profile.saveError': 'Error saving profile',

    // Expenses
    'expenses.fetchError': 'Error loading expenses',
    'expenses.deleteSuccess': 'Expense successfully deleted',
    'expenses.deleteError': 'Error deleting expense',
    'expenses.numberOfExpenses': 'Number of Expenses',
    'expenses.noExpensesFound': 'No expenses found',
    'expenses.addFirstExpense': 'Start by adding your first expense',
    'expenses.addFirstExpenseButton': 'Add First Expense',
    'expenses.itemType': 'expense',
    'expenses.category.food': 'Food',
    'expenses.category.transport': 'Transport',
    'expenses.category.utilities': 'Utilities',
    'expenses.category.entertainment': 'Entertainment',
    'expenses.category.health': 'Health',
    'expenses.category.shopping': 'Shopping',
    'expenses.category.education': 'Education',
    'expenses.category.other': 'Other',
    'expenses.paymentMethod.card': 'Card',
    'expenses.paymentMethod.cash': 'Cash',
    'expenses.paymentMethod.transfer': 'Transfer',
    'expenses.paymentMethod.check': 'Check',
    'expenses.mock.grocery.title': 'Grocery Shopping',
    'expenses.mock.grocery.description': 'Weekly Esselunga shopping',
    'expenses.mock.electricity.title': 'Electricity Bill',
    'expenses.mock.electricity.description': 'Monthly electricity bill',
    'expenses.mock.fuel.title': 'Fuel',
    'expenses.mock.fuel.description': 'Fiat 500 refueling',
    'expenses.mock.internet.title': 'Internet Subscription',
    'expenses.mock.internet.description': 'Monthly fiber fee',
    'expenses.mock.restaurant.title': 'Restaurant Dinner',
    'expenses.mock.restaurant.description': 'Dinner at Luigi\'s',
    'expenses.mock.phone.title': 'Phone Subscription',
    'expenses.mock.phone.description': 'Monthly mobile plan',

    // Bookings
    'bookings.all': 'All',
    'bookings.status.confirmed': 'Confirmed',
    'bookings.status.pending': 'Pending',
    'bookings.status.cancelled': 'Cancelled',
    'bookings.nights': 'nights',
    'bookings.note': 'Note',
    'bookings.mock.marcoRossi.guestName': 'Marco Rossi',
    'bookings.mock.marcoRossi.specialRequests': 'Late check-in',
    'bookings.mock.annaWeber.guestName': 'Anna Weber',
    'bookings.mock.annaWeber.specialRequests': 'Baby crib',
    'bookings.mock.jeanDupont.guestName': 'Jean Dupont',
    'bookings.mock.jeanDupont.source': 'Direct',
    'bookings.mock.sarahJohnson.guestName': 'Sarah Johnson',
    'bookings.mock.sarahJohnson.specialRequests': 'Parking space',
    'bookings.mock.giuseppeBianchi.guestName': 'Giuseppe Bianchi',

    // Expenses
    'expenses.title': 'Expenses Management',
    'expenses.addNew': 'Add New Expense',
    'expenses.allTime': 'All Time',
    'expenses.thisMonth': 'This Month',
    'expenses.thisYear': 'This Year',
    'expenses.sortBy': 'Sort by:',
    'expenses.date': 'Date',
    'expenses.amount': 'Amount',
    'expenses.category': 'Category',
    'expenses.myExpenses': 'My Expenses',
    'expenses.total': 'Total',
    'expenses.expense': 'Expense',
    'expenses.actions': 'Actions',
    'expenses.edit': 'Edit',
    'expenses.delete': 'Delete',
    'expenses.details': 'Expense Details',
    'expenses.description': 'Description',
    'expenses.paymentMethod': 'Payment Method',
    'expenses.editExpense': 'Edit Expense',
    'expenses.viewReceipt': 'View Receipt',
    'expenses.selectExpense': 'Select an expense to view details',
    'expenses.statistics': 'Expense Statistics',
    'expenses.totalExpenses': 'Total Expenses',
    'expenses.averageExpense': 'Average Expense',
    'expenses.byCategory': 'Expenses by Category',
    'expenses.highestExpense': 'Highest Expense',

    // B&B Bookings
    'bookings.title': 'B&B Bookings Management',
    'bookings.addNew': 'New Booking',
    'bookings.calendar': 'Calendar',
    'bookings.upcoming': 'Upcoming Bookings',
    'bookings.checkin': 'Check-in',
    'bookings.checkout': 'Check-out',
    'bookings.guests': 'Guests',
    'bookings.revenue': 'Revenue',
    'bookings.status': 'Status',
    'bookings.confirmed': 'Confirmed',
    'bookings.pending': 'Pending',
    'bookings.cancelled': 'Cancelled',
    'bookings.contact': 'Contact',
    'bookings.viewDetails': 'View Details',
    'bookings.monthlyStats': 'Monthly Statistics',
    'bookings.totalRevenue': 'Total Revenue',
    'bookings.occupancyRate': 'Occupancy Rate',
    'bookings.avgNightlyRate': 'Avg Nightly Rate',
    'bookings.totalBookings': 'Total Bookings',

    // Workouts
    'workouts.title': 'My Workouts',
    'workouts.addNew': 'New Workout',
    'workouts.recent': 'Recent Workouts',
    'workouts.duration': 'Duration',
    'workouts.exercises': 'Exercises',
    'workouts.type': 'Type',
    'workouts.intensity': 'Intensity',
    'workouts.calories': 'Calories',
    'workouts.notes': 'Notes',
    'workouts.startWorkout': 'Start Workout',
    'workouts.viewDetails': 'View Details',
    'workouts.progress': 'Progress',
    'workouts.thisWeek': 'This Week',
    'workouts.totalWorkouts': 'Total Workouts',
    'workouts.totalTime': 'Total Time',
    'workouts.avgDuration': 'Avg Duration',
    'workouts.caloriesBurned': 'Calories Burned',
    'workouts.strength': 'Strength',
    'workouts.cardio': 'Cardio',
    'workouts.flexibility': 'Flexibility',
    'workouts.sports': 'Sports',
    'workouts.low': 'Low',
    'workouts.moderate': 'Moderate',
    'workouts.high': 'High',
    'workouts.extreme': 'Extreme',
    'workouts.errorCreating': 'Could not create workout',
    'workouts.errorUpdating': 'Could not update workout',
    'workouts.errorDeleting': 'Could not delete workout',

    // Events
    'events.title': 'My Events',
    'events.addNew': 'New Event',
    'events.upcoming': 'Upcoming Events',
    'events.calendar': 'Calendar',
    'events.today': 'Today',
    'events.tomorrow': 'Tomorrow',
    'events.thisWeek': 'This Week',
    'events.time': 'Time',
    'events.location': 'Location',
    'events.attendees': 'Attendees',
    'events.reminder': 'Reminder',
    'events.edit': 'Edit',
    'events.delete': 'Delete',
    'events.personal': 'Personal',
    'events.work': 'Work',
    'events.health': 'Health',
    'events.social': 'Social',
    'events.travel': 'Travel',
    'events.other': 'Other',
    'events.noEvents': 'No events scheduled',
    'events.createFirst': 'Create your first event!',

    // Documents
    'documents.title': 'My Documents',
    'documents.upload': 'Upload Document',
    'documents.recent': 'Recent Documents',
    'documents.categories': 'Categories',
    'documents.search': 'Search documents...',
    'documents.name': 'Name',
    'documents.size': 'Size',
    'documents.modified': 'Modified',
    'documents.type': 'Type',
    'documents.download': 'Download',
    'documents.share': 'Share',
    'documents.rename': 'Rename',
    'documents.move': 'Move',
    'documents.personal': 'Personal',
    'documents.financial': 'Financial',
    'documents.legal': 'Legal',
    'documents.medical': 'Medical',
    'documents.contracts': 'Contracts',
    'documents.taxes': 'Taxes',
    'documents.insurance': 'Insurance',
    'documents.other': 'Other',
    'documents.totalStorage': 'Total Storage',
    'documents.usedStorage': 'Used Storage',
    'documents.freeStorage': 'Free Storage',

    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.account': 'Account',
    'settings.about': 'About',
    'settings.languageDesc': 'Select interface language',
    'settings.themeDesc': 'Choose between light or dark theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.auto': 'Auto',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.deadlineReminders': 'Deadline Reminders',
    'settings.save': 'Save Changes',
    'settings.cancel': 'Cancel',
    'settings.version': 'Version',
    'settings.developer': 'Developer',

    // Profile
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Enter your name',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'Enter your email',
    'profile.phone': 'Phone',
    'profile.phonePlaceholder': 'Enter your phone number',
    'profile.address': 'Address',
    'profile.addressPlaceholder': 'Enter your address',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us a bit about yourself...',
    'profile.fetchError': 'Error loading profile',
    'profile.saveSuccess': 'Profile saved successfully',
    'profile.saveError': 'Error saving profile',

    // Common
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.share': 'Share',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.warning': 'Warning',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.info': 'Info',
    'common.logout': 'Sign out',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('vitaapp-language');
    return (saved as Language) || 'it'; // Default italiano
  });

  useEffect(() => {
    localStorage.setItem('vitaapp-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};