import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations catalog following AI Coding Guidelines
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.deadlines': 'Deadlines',
    'nav.properties': 'Properties',
    'nav.vehicles': 'Vehicles',
    'nav.expenses': 'Expenses',
    'nav.bookings': 'B&B Bookings',
    'nav.workouts': 'Workouts',
    'nav.events': 'Events',
    'nav.documents': 'Documents',
    'nav.contacts': 'Contacts',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',

    // Dashboard
    'dashboard.welcome': 'Welcome to VitaApp',
    'dashboard.subtitle': 'Your complete solution for managing properties, vehicles, expenses and more. Simplify your life with an intuitive and powerful dashboard.',
    'dashboard.getStarted': 'Get Started',
    'dashboard.learnMore': 'Learn More',
    'dashboard.pendingDeadlines': 'Pending Deadlines',
    'dashboard.totalExpenses': 'Total Expenses (Last 30d)',
    'dashboard.activeProperties': 'Active Properties',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.upcomingDeadlinesList': 'Upcoming Deadlines',
    'dashboard.recentExpenses': 'Recent Expenses',
    'dashboard.viewAll': 'View All',
    'dashboard.completed': 'completed',
    'dashboard.total': 'Total',
    'dashboard.fromRecentTransactions': 'From recent transactions',
    'dashboard.rented': 'Rented',
    'dashboard.vacant': 'Vacant',
    'dashboard.next': 'Next',
    'dashboard.noDeadlines': 'No pending deadlines. Well done!',
    'dashboard.noExpenses': 'No expenses recorded recently.',
    'dashboard.activityOverview': 'Activity Overview',
    'dashboard.daysAgo': 'days ago',
    'dashboard.days': 'days',

    // Properties
    'properties.title': 'Property Management',
    'properties.addNew': 'Add New Property',
    'properties.myProperties': 'My Properties',
    'properties.selectPrompt': 'Select a property to view details',
    'properties.table.property': 'Property',
    'properties.table.type': 'Type',
    'properties.table.size': 'Size',
    'properties.table.currentValue': 'Current Value',
    'properties.table.actions': 'Actions',
    'properties.details.title': 'Property Details',
    'properties.details.type': 'Type',
    'properties.details.size': 'Size',
    'properties.details.purchaseDate': 'Purchase Date',
    'properties.details.purchasePrice': 'Purchase Price',
    'properties.details.currentValue': 'Current Value',
    'properties.details.valueChange': 'Value Change',
    'properties.details.notes': 'Notes',
    'properties.details.edit': 'Edit Property',
    'properties.details.viewDocuments': 'View Documents',
    'properties.mock.mainApartment.name': 'Main Apartment',
    'properties.mock.mainApartment.type': 'Apartment',
    'properties.mock.mainApartment.notes': 'Primary residence',
    'properties.mock.beachHouse.name': 'Beach House',
    'properties.mock.beachHouse.type': 'House',
    'properties.mock.beachHouse.notes': 'Vacation property and B&B rental',
    'properties.mock.mountainCabin.name': 'Mountain Cabin',
    'properties.mock.mountainCabin.type': 'Cabin',
    'properties.mock.mountainCabin.notes': 'Winter vacation property',

    // Deadlines
    'deadlines.title': 'Deadline Management',
    'deadlines.addNew': 'Add New Deadline',
    'deadlines.filter.all': 'All',
    'deadlines.filter.upcoming': 'Upcoming',
    'deadlines.filter.completed': 'Completed',
    'deadlines.sortBy': 'Sort by',
    'deadlines.sort.dueDate': 'Due Date',
    'deadlines.sort.title': 'Title',
    'deadlines.sort.category': 'Category',
    'deadlines.table.status': 'Status',
    'deadlines.table.title': 'Title',
    'deadlines.table.dueDate': 'Due Date',
    'deadlines.table.category': 'Category',
    'deadlines.table.remainingTime': 'Remaining Time',
    'deadlines.table.actions': 'Actions',
    'deadlines.status.completed': 'Completed',
    'deadlines.days': 'days',
    'deadlines.category.taxes': 'Taxes',
    'deadlines.category.vehicle': 'Vehicle',
    'deadlines.mock.imuFirst': 'First IMU Payment',
    'deadlines.mock.imuFirstDesc': 'First installment of municipal property tax',
    'deadlines.mock.carInsurance': 'Car Insurance Renewal',
    'deadlines.mock.carInsuranceDesc': 'Annual car insurance renewal',
    'deadlines.mock.tari': 'TARI Payment',
    'deadlines.mock.tariDesc': 'Annual waste management tax payment',
    'deadlines.mock.imuSecond': 'Second IMU Payment',
    'deadlines.mock.imuSecondDesc': 'Second installment of municipal property tax',
    'deadlines.mock.carTax': 'Car Tax Renewal',
    'deadlines.mock.carTaxDesc': 'Annual car tax renewal',
    'deadlines.mock.vehicleInspection': 'Vehicle Inspection',
    'deadlines.mock.vehicleInspectionDesc': 'Periodic technical inspection of the vehicle',

    // Vehicles
    'vehicles.title': 'Vehicle Management',
    'vehicles.addNew': 'Add New Vehicle',
    'vehicles.myVehicles': 'My Vehicles',
    'vehicles.selectPrompt': 'Select a vehicle to view details',
    'vehicles.type.car': 'Car',
    'vehicles.type.motorcycle': 'Motorcycle',
    'vehicles.table.vehicle': 'Vehicle',
    'vehicles.table.type': 'Type',
    'vehicles.table.licensePlate': 'License Plate',
    'vehicles.table.insuranceExpiry': 'Insurance Expiry',
    'vehicles.table.actions': 'Actions',
    'vehicles.details.title': 'Vehicle Details',
    'vehicles.details.type': 'Type',
    'vehicles.details.licensePlate': 'License Plate',
    'vehicles.details.purchaseDate': 'Purchase Date',
    'vehicles.details.purchasePrice': 'Purchase Price',
    'vehicles.details.currentValue': 'Current Value',
    'vehicles.details.valueChange': 'Value Change',
    'vehicles.details.importantDates': 'Important Dates',
    'vehicles.details.insuranceRenewal': 'Insurance Renewal',
    'vehicles.details.registration': 'Registration',
    'vehicles.details.annualCost': 'Annual Cost',
    'vehicles.details.inspection': 'Inspection',
    'vehicles.details.lastInspection': 'Last Inspection',
    'vehicles.details.daysRemaining': 'days remaining',
    'vehicles.details.edit': 'Edit Vehicle',
    'vehicles.details.viewDocuments': 'View Documents',
    'vehicles.mock.dailyDriver.name': 'Daily Driver',
    'vehicles.mock.weekendRide.name': 'Weekend Ride',

    // Expenses
    'expenses.title': 'Expense Management',
    'expenses.addNew': 'Add New Expense',
    'expenses.allTime': 'All Time',
    'expenses.thisMonth': 'This Month',
    'expenses.thisYear': 'This Year',
    'expenses.sortBy': 'Sort by:',
    'expenses.date': 'Date',
    'expenses.amount': 'Amount',
    'expenses.category': 'Category',
    'expenses.myExpenses': 'My Expenses',
    'expenses.total': 'Total',
    'expenses.expense': 'Expense',
    'expenses.actions': 'Actions',
    'expenses.description': 'Description',
    'expenses.paymentMethod': 'Payment Method',
    'expenses.recurring': 'Recurring Expense',
    'expenses.frequency': 'Frequency',

    // Expense Form
    'expenses.form.amountHelper': 'Enter the expense amount',
    'expenses.form.selectCategory': 'Select a category',
    'expenses.form.descriptionPlaceholder': 'Enter a description',
    'expenses.form.selectFrequency': 'Select frequency',
    'expenses.form.editSummary': 'Expense Summary',
    'expenses.form.updateExpense': 'Update Expense',
    'expenses.form.createExpense': 'Create Expense',
    'expenses.form.debugInfo': 'Debug Information',
    'expenses.form.addDescription': 'Add New Expense',
    'expenses.form.editDescription': 'Edit Expense',

    // Expense Categories
    'expenses.category.food': 'Food & Dining',
    'expenses.category.transport': 'Transportation',
    'expenses.category.utilities': 'Utilities',
    'expenses.category.entertainment': 'Entertainment',
    'expenses.category.health': 'Health & Medical',
    'expenses.category.shopping': 'Shopping',
    'expenses.category.education': 'Education',
    'expenses.category.other': 'Other',

    // Payment Methods
    'expenses.paymentMethod.card': 'Card',
    'expenses.paymentMethod.cash': 'Cash',
    'expenses.paymentMethod.transfer': 'Bank Transfer',
    'expenses.paymentMethod.check': 'Check',

    // Frequencies
    'expenses.frequency.daily': 'Daily',
    'expenses.frequency.weekly': 'Weekly',
    'expenses.frequency.monthly': 'Monthly',
    'expenses.frequency.bimonthly': 'Bimonthly',
    'expenses.frequency.quarterly': 'Quarterly',

    // Events
    'events.title': 'Event Management',
    'events.addNew': 'Add New Event',
    'events.loadError': 'Could not load events from the JSON database',
    'events.deleteError': 'Could not delete the event',
    'events.confirmDelete': 'Are you sure you want to delete this event?',
    'events.loading': 'Loading events from JSON database...',
    'events.dataSource': 'Data loaded from',
    'events.calendarView': 'Calendar view not yet implemented.',
    'events.upcomingEvents': 'Upcoming Events',
    'events.today': 'Today',
    'events.tomorrow': 'Tomorrow',
    'events.thisWeek': 'This Week',
    'events.filters.all': 'All',
    'events.filters.today': 'Today',
    'events.filters.week': 'This Week',
    'events.filters.work': 'Work',
    'events.filters.health': 'Health',
    'events.filters.social': 'Social',
    'events.filters.travel': 'Travel',
    'events.filters.personal': 'Personal',
    'events.filters.other': 'Other',

    // Documents
    'documents.title': 'Document Management',
    'documents.addNew': 'Add New Document',
    'documents.uploadDocument': 'Upload Document',
    'documents.name': 'Document Name',
    'documents.type': 'Type',
    'documents.category': 'Category',
    'documents.tags': 'Tags',
    'documents.commaSeparated': 'comma separated',
    'documents.file': 'File',
    'documents.dragAndDrop': 'Drag and drop your file here',
    'documents.orClickToUpload': 'or click to upload',
    'documents.browseFiles': 'Browse Files',
    'documents.upload': 'Upload',
    'documents.loadError': 'Could not load documents from the JSON database',
    'documents.deleteError': 'Could not delete the document',
    'documents.loading': 'Loading documents from JSON database...',
    'documents.storageUsage': 'Storage Usage',
    'documents.searchPlaceholder': 'Search documents...',
    'documents.filterByCategory': 'Filter by category',
    'documents.sortBy': 'Sort by',
    'documents.sort.name': 'Name',
    'documents.sort.date': 'Date',
    'documents.sort.size': 'Size',
    'documents.noDocuments': 'No documents found',
    'documents.noDocumentsMessage': 'Start by uploading your first document.',
    'documents.uploadFirst': 'Upload First Document',
    'documents.table.name': 'Name',
    'documents.table.category': 'Category',
    'documents.table.dateModified': 'Date Modified',
    'documents.table.size': 'Size',
    'documents.table.actions': 'Actions',
    'documents.actions.download': 'Download',
    'documents.actions.share': 'Share',
    'documents.actions.edit': 'Edit',
    'documents.actions.delete': 'Delete',
    'documents.deleteTitle': 'Delete Document',
    'documents.deleteMessage': 'Are you sure you want to delete this document? This action cannot be undone.',

    // Categories
    'categories.work': 'Work',
    'categories.health': 'Health',
    'categories.social': 'Social',
    'categories.travel': 'Travel',
    'categories.personal': 'Personal',
    'categories.financial': 'Financial',
    'categories.legal': 'Legal',
    'categories.medical': 'Medical',
    'categories.contracts': 'Contracts',
    'categories.taxes': 'Taxes',
    'categories.insurance': 'Insurance',
    'categories.other': 'Other',

    // Dates
    'dates.today': 'Today',
    'dates.tomorrow': 'Tomorrow',
    'dates.thisWeek': 'This Week',

    // Common
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.calendar': 'Calendar',
    'common.list': 'List',
    'common.cancel': 'Cancel',

    // ... other translations
  },
  it: {
    // Navigazione
    'nav.dashboard': 'Dashboard',
    'nav.deadlines': 'Scadenze',
    'nav.properties': 'Proprietà',
    'nav.vehicles': 'Veicoli',
    'nav.expenses': 'Spese',
    'nav.bookings': 'Prenotazioni B&B',
    'nav.workouts': 'Allenamenti',
    'nav.events': 'Eventi',
    'nav.documents': 'Documenti',
    'nav.contacts': 'Contatti',
    'nav.profile': 'Profilo',
    'nav.settings': 'Impostazioni',

    // Dashboard
    'dashboard.welcome': 'Benvenuto in VitaApp',
    'dashboard.subtitle': 'La tua soluzione completa per gestire proprietà, veicoli, spese e altro. Semplifica la tua vita con una dashboard intuitiva e potente.',
    'dashboard.getStarted': 'Inizia',
    'dashboard.learnMore': 'Scopri di più',
    'dashboard.pendingDeadlines': 'Scadenze in sospeso',
    'dashboard.totalExpenses': 'Spese totali (Ultimi 30g)',
    'dashboard.activeProperties': 'Proprietà attive',
    'dashboard.upcomingEvents': 'Eventi imminenti',
    'dashboard.upcomingDeadlinesList': 'Prossime scadenze',
    'dashboard.recentExpenses': 'Spese recenti',
    'dashboard.viewAll': 'Vedi tutto',
    'dashboard.completed': 'completate',
    'dashboard.total': 'Totale',
    'dashboard.fromRecentTransactions': 'Da transazioni recenti',
    'dashboard.rented': 'Affittate',
    'dashboard.vacant': 'Libere',
    'dashboard.next': 'Prossimo',
    'dashboard.noDeadlines': 'Nessuna scadenza in sospeso. Ben fatto!',
    'dashboard.noExpenses': 'Nessuna spesa registrata recentemente.',
    'dashboard.activityOverview': 'Panoramica attività',
    'dashboard.daysAgo': 'giorni fa',
    'dashboard.days': 'giorni',

    // Properties
    'properties.title': 'Gestione Proprietà',
    'properties.addNew': 'Aggiungi Nuova Proprietà',
    'properties.myProperties': 'Le Mie Proprietà',
    'properties.selectPrompt': 'Seleziona una proprietà per visualizzare i dettagli',
    'properties.table.property': 'Proprietà',
    'properties.table.type': 'Tipo',
    'properties.table.size': 'Dimensione',
    'properties.table.currentValue': 'Valore Attuale',
    'properties.table.actions': 'Azioni',
    'properties.details.title': 'Dettagli Proprietà',
    'properties.details.type': 'Tipo',
    'properties.details.size': 'Dimensione',
    'properties.details.purchaseDate': 'Data Acquisto',
    'properties.details.purchasePrice': 'Prezzo Acquisto',
    'properties.details.currentValue': 'Valore Attuale',
    'properties.details.valueChange': 'Variazione Valore',
    'properties.details.notes': 'Note',
    'properties.details.edit': 'Modifica Proprietà',
    'properties.details.viewDocuments': 'Visualizza Documenti',
    'properties.mock.mainApartment.name': 'Appartamento Principale',
    'properties.mock.mainApartment.type': 'Appartamento',
    'properties.mock.mainApartment.notes': 'Residenza principale',
    'properties.mock.beachHouse.name': 'Casa al Mare',
    'properties.mock.beachHouse.type': 'Casa',
    'properties.mock.beachHouse.notes': 'Proprietà vacanze e affitto B&B',
    'properties.mock.mountainCabin.name': 'Baita in Montagna',
    'properties.mock.mountainCabin.type': 'Baita',
    'properties.mock.mountainCabin.notes': 'Proprietà vacanze invernali',

    // Deadlines
    'deadlines.title': 'Gestione Scadenze',
    'deadlines.addNew': 'Aggiungi Nuova Scadenza',
    'deadlines.filter.all': 'Tutte',
    'deadlines.filter.upcoming': 'Imminenti',
    'deadlines.filter.completed': 'Completate',
    'deadlines.sortBy': 'Ordina per',
    'deadlines.sort.dueDate': 'Data Scadenza',
    'deadlines.sort.title': 'Titolo',
    'deadlines.sort.category': 'Categoria',
    'deadlines.table.status': 'Stato',
    'deadlines.table.title': 'Titolo',
    'deadlines.table.dueDate': 'Data Scadenza',
    'deadlines.table.category': 'Categoria',
    'deadlines.table.remainingTime': 'Tempo Rimanente',
    'deadlines.table.actions': 'Azioni',
    'deadlines.status.completed': 'Completata',
    'deadlines.days': 'giorni',
    'deadlines.category.taxes': 'Tasse',
    'deadlines.category.vehicle': 'Veicolo',
    'deadlines.mock.imuFirst': 'Primo Pagamento IMU',
    'deadlines.mock.imuFirstDesc': 'Prima rata imposta municipale sugli immobili',
    'deadlines.mock.carInsurance': 'Rinnovo Assicurazione Auto',
    'deadlines.mock.carInsuranceDesc': 'Rinnovo annuale assicurazione auto',
    'deadlines.mock.tari': 'Pagamento TARI',
    'deadlines.mock.tariDesc': 'Pagamento annuale tassa rifiuti',
    'deadlines.mock.imuSecond': 'Secondo Pagamento IMU',
    'deadlines.mock.imuSecondDesc': 'Seconda rata imposta municipale sugli immobili',
    'deadlines.mock.carTax': 'Rinnovo Bollo Auto',
    'deadlines.mock.carTaxDesc': 'Rinnovo annuale bollo auto',
    'deadlines.mock.vehicleInspection': 'Revisione Veicolo',
    'deadlines.mock.vehicleInspectionDesc': 'Ispezione tecnica periodica del veicolo',

    // Vehicles
    'vehicles.title': 'Gestione Veicoli',
    'vehicles.addNew': 'Aggiungi Nuovo Veicolo',
    'vehicles.myVehicles': 'I Miei Veicoli',
    'vehicles.selectPrompt': 'Seleziona un veicolo per visualizzare i dettagli',
    'vehicles.type.car': 'Auto',
    'vehicles.type.motorcycle': 'Moto',
    'vehicles.table.vehicle': 'Veicolo',
    'vehicles.table.type': 'Tipo',
    'vehicles.table.licensePlate': 'Targa',
    'vehicles.table.insuranceExpiry': 'Scadenza Assicurazione',
    'vehicles.table.actions': 'Azioni',
    'vehicles.details.title': 'Dettagli Veicolo',
    'vehicles.details.type': 'Tipo',
    'vehicles.details.licensePlate': 'Targa',
    'vehicles.details.purchaseDate': 'Data Acquisto',
    'vehicles.details.purchasePrice': 'Prezzo Acquisto',
    'vehicles.details.currentValue': 'Valore Attuale',
    'vehicles.details.valueChange': 'Variazione Valore',
    'vehicles.details.importantDates': 'Date Importanti',
    'vehicles.details.insuranceRenewal': 'Rinnovo Assicurazione',
    'vehicles.details.registration': 'Immatricolazione',
    'vehicles.details.annualCost': 'Costo Annuale',
    'vehicles.details.inspection': 'Revisione',
    'vehicles.details.lastInspection': 'Ultima Revisione',
    'vehicles.details.daysRemaining': 'giorni rimanenti',
    'vehicles.details.edit': 'Modifica Veicolo',
    'vehicles.details.viewDocuments': 'Visualizza Documenti',
    'vehicles.mock.dailyDriver.name': 'Auto Quotidiana',
    'vehicles.mock.weekendRide.name': 'Auto del Weekend',

    // Expenses
    'expenses.title': 'Gestione Spese',
    'expenses.addNew': 'Aggiungi Nuova Spesa',
    'expenses.allTime': 'Tutto il Periodo',
    'expenses.thisMonth': 'Questo Mese',
    'expenses.thisYear': 'Quest\'Anno',
    'expenses.sortBy': 'Ordina per:',
    'expenses.date': 'Data',
    'expenses.amount': 'Importo',
    'expenses.category': 'Categoria',
    'expenses.myExpenses': 'Le Mie Spese',
    'expenses.total': 'Totale',
    'expenses.expense': 'Spesa',
    'expenses.actions': 'Azioni',
    'expenses.description': 'Descrizione',
    'expenses.paymentMethod': 'Metodo di Pagamento',
    'expenses.recurring': 'Spesa Ricorrente',
    'expenses.frequency': 'Frequenza',

    // Expense Form
    'expenses.form.amountHelper': 'Inserisci l\'importo della spesa',
    'expenses.form.selectCategory': 'Seleziona una categoria',
    'expenses.form.descriptionPlaceholder': 'Inserisci una descrizione',
    'expenses.form.selectFrequency': 'Seleziona la frequenza',
    'expenses.form.editSummary': 'Riepilogo Spesa',
    'expenses.form.updateExpense': 'Aggiorna Spesa',
    'expenses.form.createExpense': 'Crea Spesa',
    'expenses.form.debugInfo': 'Informazioni di Debug',
    'expenses.form.addDescription': 'Aggiungi Nuova Spesa',
    'expenses.form.editDescription': 'Modifica Spesa',

    // Expense Categories
    'expenses.category.food': 'Cibo & Ristorazione',
    'expenses.category.transport': 'Trasporti',
    'expenses.category.utilities': 'Utenze',
    'expenses.category.entertainment': 'Intrattenimento',
    'expenses.category.health': 'Salute & Medicina',
    'expenses.category.shopping': 'Shopping',
    'expenses.category.education': 'Istruzione',
    'expenses.category.other': 'Altro',

    // Payment Methods
    'expenses.paymentMethod.card': 'Carta',
    'expenses.paymentMethod.cash': 'Contanti',
    'expenses.paymentMethod.transfer': 'Bonifico Bancario',
    'expenses.paymentMethod.check': 'Assegno',

    // Frequencies
    'expenses.frequency.daily': 'Giornaliera',
    'expenses.frequency.weekly': 'Settimanale',
    'expenses.frequency.monthly': 'Mensile',
    'expenses.frequency.bimonthly': 'Bimestrale',
    'expenses.frequency.quarterly': 'Trimestrale',
    'expenses.frequency.yearly': 'Annuale',

    // Validation Messages
    'expenses.validation.amountRequired': 'L\'importo è obbligatorio',
    'expenses.validation.amountInvalid': 'L\'importo deve essere maggiore di zero',
    'expenses.validation.amountTooHigh': 'L\'importo è troppo alto',
    'expenses.validation.categoryRequired': 'La categoria è obbligatoria',
    'expenses.validation.categoryNotSelected': 'Nessuna categoria selezionata',
    'expenses.validation.dateRequired': 'La data è obbligatoria',
    'expenses.validation.dateFuture': 'La data non può essere nel futuro',
    'expenses.validation.dateTooOld': 'La data è troppo vecchia',
    'expenses.validation.dateNotSpecified': 'Non specificata',
    'expenses.validation.descriptionTooLong': 'La descrizione è troppo lunga (massimo 500 caratteri)',
    'expenses.validation.frequencyRequired': 'La frequenza è obbligatoria per le spese ricorrenti',

    // Workouts
    'workouts.title': 'Gestione Allenamenti',
    'workouts.addNew': 'Aggiungi Nuovo Allenamento',
    'workouts.startWorkout': 'Inizia Allenamento',
    'workouts.editWorkout': 'Modifica Allenamento',
    'workouts.addWorkout': 'Aggiungi Allenamento',
    'workouts.totalWorkouts': 'Totale Allenamenti',
    'workouts.totalTime': 'Tempo Totale',
    'workouts.caloriesBurned': 'Calorie Bruciate',
    'workouts.progress': 'Progresso',
    'workouts.thisWeek': 'Questa Settimana',
    'workouts.avgDuration': 'Durata Media',
    'workouts.vsLastWeek': 'vs Settimana Scorsa',
    'workouts.all': 'Tutti gli Allenamenti',
    'workouts.recent': 'Allenamenti Recenti',
    'workouts.viewDetails': 'Vedi Dettagli',
    'workouts.name': 'Nome Allenamento',
    'workouts.duration': 'Durata',
    'workouts.calories': 'Calorie',
    'workouts.date': 'Data',
    'workouts.exercises': 'Esercizi',
    'workouts.addExercise': 'Aggiungi esercizio',
    'workouts.noExercises': 'Nessun esercizio aggiunto',
    'workouts.notes': 'Note',
    'workouts.errorCreating': 'Errore durante la creazione dell\'allenamento',
    'workouts.errorUpdating': 'Errore durante l\'aggiornamento dell\'allenamento',
    'workouts.errorDeleting': 'Errore durante l\'eliminazione dell\'allenamento',
    
    'workouts.type.label': 'Tipo di Allenamento',
    'workouts.type.strength': 'Forza',
    'workouts.type.cardio': 'Cardio',
    'workouts.type.flexibility': 'Flessibilità',
    'workouts.type.sports': 'Sport',
    
    'workouts.intensity.label': 'Intensità',
    'workouts.intensity.low': 'Bassa',
    'workouts.intensity.moderate': 'Moderata',
    'workouts.intensity.high': 'Alta',
    'workouts.intensity.extreme': 'Estrema',
    
    'workouts.errors.nameRequired': 'Il nome dell\'allenamento è obbligatorio',
    'workouts.errors.dateRequired': 'La data è obbligatoria',
    'workouts.errors.durationPositive': 'La durata deve essere maggiore di zero',

    // Eventi
    'events.title': 'Gestione Eventi',
    'events.addNew': 'Aggiungi Nuovo Evento',
    'events.loadError': 'Impossibile caricare gli eventi dal database JSON',
    'events.deleteError': 'Impossibile eliminare l\'evento',
    'events.confirmDelete': 'Sei sicuro di voler eliminare questo evento?',
    'events.loading': 'Caricamento eventi dal database JSON...',
    'events.dataSource': 'Dati caricati da',
    'events.calendarView': 'La vista calendario non è ancora implementata.',
    'events.upcomingEvents': 'Eventi Prossimi',
    'events.today': 'Oggi',
    'events.tomorrow': 'Domani',
    'events.thisWeek': 'Questa settimana',
    'events.filters.all': 'Tutti',
    'events.filters.today': 'Oggi',
    'events.filters.week': 'Questa settimana',
    'events.filters.work': 'Lavoro',
    'events.filters.health': 'Salute',
    'events.filters.social': 'Sociale',
    'events.filters.travel': 'Viaggio',
    'events.filters.personal': 'Personale',
    'events.filters.other': 'Altro',

    // Documenti
    'documents.title': 'Gestione Documenti',
    'documents.addNew': 'Aggiungi Nuovo Documento',
    'documents.uploadDocument': 'Carica Documento',
    'documents.name': 'Nome Documento',
    'documents.type': 'Tipo',
    'documents.category': 'Categoria',
    'documents.tags': 'Tag',
    'documents.commaSeparated': 'separati da virgola',
    'documents.file': 'File',
    'documents.dragAndDrop': 'Trascina e rilascia il tuo file qui',
    'documents.orClickToUpload': 'o clicca per caricare',
    'documents.browseFiles': 'Sfoglia File',
    'documents.upload': 'Carica',
    'documents.loadError': 'Impossibile caricare i documenti dal database JSON',
    'documents.deleteError': 'Impossibile eliminare il documento',
    'documents.loading': 'Caricamento documenti dal database JSON...',
    'documents.storageUsage': 'Utilizzo Storage',
    'documents.searchPlaceholder': 'Cerca documenti...',
    'documents.filterByCategory': 'Filtra per categoria',
    'documents.sortBy': 'Ordina per',
    'documents.sort.name': 'Nome',
    'documents.sort.date': 'Data',
    'documents.sort.size': 'Dimensione',
    'documents.noDocuments': 'Nessun documento trovato',
    'documents.noDocumentsMessage': 'Inizia caricando il tuo primo documento.',
    'documents.uploadFirst': 'Carica Primo Documento',
    'documents.table.name': 'Nome',
    'documents.table.category': 'Categoria',
    'documents.table.dateModified': 'Data Modifica',
    'documents.table.size': 'Dimensione',
    'documents.table.actions': 'Azioni',
    'documents.actions.download': 'Scarica',
    'documents.actions.share': 'Condividi',
    'documents.actions.edit': 'Modifica',
    'documents.actions.delete': 'Elimina',
    'documents.deleteTitle': 'Elimina Documento',
    'documents.deleteMessage': 'Sei sicuro di voler eliminare questo documento? Questa azione non può essere annullata.',

    // Categorie
    'categories.work': 'Lavoro',
    'categories.health': 'Salute',
    'categories.social': 'Sociale',
    'categories.travel': 'Viaggio',
    'categories.personal': 'Personale',
    'categories.financial': 'Finanziario',
    'categories.legal': 'Legale',
    'categories.medical': 'Medico',
    'categories.contracts': 'Contratti',
    'categories.taxes': 'Tasse',
    'categories.insurance': 'Assicurazioni',
    'categories.other': 'Altro',

    // Date
    'dates.today': 'Oggi',
    'dates.tomorrow': 'Domani',
    'dates.thisWeek': 'Questa Settimana',

    // Comune
    'common.error': 'Errore',
    'common.retry': 'Riprova',
    'common.calendar': 'Calendario',
    'common.list': 'Lista',

    // Comune
    'common.cancel': 'Annulla',
    'common.characters': 'caratteri',
    'common.search': 'Cerca',
    'common.add': 'Aggiungi',
    'common.save': 'Salva',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
  }
};

const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get the language from localStorage
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage as Language) || 'en';
  });

  useEffect(() => {
    // Save the language preference to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const currentTranslations = translations[language] || translations.en;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LanguageProvider, useLanguage };